# Generated by Django 4.1.9 on 2023-08-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='update_date',
            new_name='update_desc',
        ),
    ]
